my_string = (input("Придумайте пароль "))
print(f"Ваш пароль - {my_string}!")
print("состоит из")
print(len(my_string))
print("символов")
my_string = (input("Напишите пароль в нижнем регистре "))
print(my_string .upper())
print("Я говорю в нижнем регистре " "!!!" )
my_string = (input("Лааадно пиши Верхний регистр нажми capslock "))
print(my_string .lower())
print("ТЫ ИЗДЕВАЕШЬСЯ " "???")
my_string = (input("Ну хорошо , придумай пароль состоящий из двух или более слов "))
print(my_string.replace(' ', ''))
print('А пробелы ??? , я за тебя ставить буду ' '???')
name = (input('Тебя как звать граммотей ? '))
print(name[1])
print('нет такого имени ! , попробуй еще раз')
name = (input("введите Ваше имя "))
print(name[-1])
print('Нам кажеться ты пропуcкаешь буквы:)')

